### ISSUE TITLE
Whole word filtering inconsistent

### ISSUE THREAD

**Issue by jtrenta** [boarder2/Latest-Chatty-8#85]
I think the whole word filtering might not work if there are shacktags around the word/words you are trying to filter.  So if you wanted to filter "example" but someone put r[example]r in, it wouldn't consider that a match.

**Comment by boarder2** [comment]
Turns out this is only an issue if you use "whole word" matching, which puts spaces surrounding the match.

For example if you want to filter on "example" and choose whole word matching it will be looking for " example ".

In order to fix this, it would require stripping of all markup tags.

Due to the processing time involved in doing that, I'm not sure I'm very likely to implement this any time soon.  A naive regex replace to remove markup might be sufficient enough to get most of the cases.

Depending on what you're trying to filter, not choosing whole word matching may work.  However, if you have a non-whole word filter on "example" it would also match against "Thisisanexample", which may not be desirable.

**Comment by boarder2** [comment]
Just kidding, this was easy to fix. It'll be in the next release.
